# Install Spark-HPC pre-requisite software packages
# NOTE: remote_user needs to be changed to the account
# name you use to connect to the machines where you will
# perform the install. This account needs to have sudo
# permissions.

---
- hosts: install_nodes
  connection: ssh
  become: yes
  remote_user: root
  vars:
    current_dir: ~/sparkle/deploy/dependent-modules

  tasks:

    - name: Include variables from configuration file for Debian
      include_vars: vars/sparkle-vars-debian.yml
      when: ansible_os_family == 'Debian'

    - name: Install applications for Debian
      apt: name="{{item}}" state=latest update_cache=yes
      with_items: "{{applications_to_install}}"
      when: ansible_os_family == 'Debian'

    - name: Install libraries for Debian
      apt: name="{{item}}" state=latest update_cache=yes
      with_items: "{{libraries_to_install}}"
      when: ansible_os_family == 'Debian'

    - name: Include variables from configuration file for RHEL
      include_vars: vars/sparkle-vars-rhel.yml
      when: ansible_os_family == 'RedHat'

    - name: Add IUS Repository
      yum: name="https://centos7.iuscommunity.org/ius-release.rpm"
      when: ansible_os_family == 'RedHat'

    - name: Install applications for RHEL
      yum: name="{{item}}" state=latest update_cache=yes
      with_items: "{{applications_to_install}}"
      when: ansible_os_family == 'RedHat'

    - name: Install libraries for RHEL
      yum: name="{{item}}" state=latest update_cache=yes
      with_items: "{{libraries_to_install}}"
      when: ansible_os_family == 'RedHat'

    - name: Fix symlink for tcmalloc
      shell: "{{current_dir}}/scripts/fix_tcmalloc_symlink.sh"
